# Generate Trading Signals

In [1]:
import numpy as np

## Data type conversion

In [2]:
arr = np.arange(10)
print(arr)
print(type(arr))
print(arr.dtype)

[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>
int64


In [3]:
float_arr = arr / 2
print(float_arr)
print(type(float_arr))
print(float_arr.dtype)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
<class 'numpy.ndarray'>
float64


In [4]:
int_arr = float_arr.astype(np.int64)
print(int_arr)
print(type(int_arr))
print(int_arr.dtype)

[0 0 1 1 2 2 3 3 4 4]
<class 'numpy.ndarray'>
int64


## Signals


In [5]:
prices = np.array([1, 3, -2, 9, 5, 7, 2])
prices

array([ 1,  3, -2,  9,  5,  7,  2])

In [6]:
signal_one = prices > 2
signal_three = prices > 4

print(signal_one)
print(signal_three)

[False  True False  True  True  True False]
[False False False  True  True  True False]


In [7]:
signal_one = signal_one.astype(np.int)
signal_three = signal_three.astype(np.int)

print(signal_one)
print(signal_three)

[0 1 0 1 1 1 0]
[0 0 0 1 1 1 0]


## Signals to positions

- buy 1 share when price > 2
- buy 3 shares when price > 4

In [8]:
position_one = 1 * signal_one
position_three = 3 * signal_three

print(position_one)
print(position_three)

[0 1 0 1 1 1 0]
[0 0 0 3 3 3 0]


In [9]:
long_positions = position_one + position_three
print(long_positions)

[0 1 0 4 4 4 0]
